import type { Metadata } from 'next'
import Link from 'next/link'
import { Poppins } from 'next/font/google'
import { ChartColumnBigIcon } from 'lucide-react'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton
} from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { Button } from '@/components/ui/button'
import UserDropDown from '@/components/UserDropDown'
import './globals.css'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'tp10 Tracker',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="font-bold text-2xl flex gap-1 items-center"
            >
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center">
                  <Button asChild variant="link" className="text-white">
                    <SignInButton />
                  </Button>
                  <Button asChild variant="link" className="text-white">
                    <SignUpButton />
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <UserDropDown />
              </SignedIn>
            </div>
          </nav>
          {children}
          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout
